### ISSUE TITLE
Error importing ping from __main__ 

### ISSUE THREAD

**Issue by cpstrommen** [LibreCS/plcd#5]
Error calling ping from __main__ on execution
```bash
% python3 -m plcd
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/plcd/__main__.py", line 3, in <module>
    from ping import main
ModuleNotFoundError: No module named 'ping'
```

**Comment by cpstrommen** [comment]
Fixed with project structure updates
