### ISSUE TITLE
Issue in `configure()` with `input()`

### ISSUE THREAD

**Issue by cpstrommen** [LibreCS/plcd#6]
This error on the run section of `run-dist.yml` gh action:
```bash
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/runpy.py", line [19](https://github.com/LibreCS/plcd/runs/7613589288?check_suite_focus=true#step:6:20)3, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plcd/__main__.py", line 3, in <module>
    from plcd.ping import main
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plcd/ping.py", line [28](https://github.com/LibreCS/plcd/runs/7613589288?check_suite_focus=true#step:6:29)6, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plcd/ping.py", line 199, in main
    netLocationPLC = configure()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plcd/ping.py", line 47, in configure
    hostUsrIn = input(addressInMsg)
```
Test different configurations of the action, might be a problem with the input function and gh runners.

**Comment by cpstrommen** [comment]
Issue magnified and centralized in [this issue](https://github.com/LibreCS/plcd/issues/9)

This thread is deprecated
